import { getBackend } from '$lib/backend';
export interface ChatFile { label?: string; local_reference?: boolean; id: string; name: string; path: string; mime: string; size: number; sha256: string }
export interface ChatTaskPlan {goal:string;todos:{id:string;title:string;status:'pending'|'in_progress'|'completed'}[];updated_ms:number;progress?:{message:string;phase?:string;percent?:number;todo_id?:string;updated_ms:number}}
export interface ChatMessage { received_by?:string[]; agent_id?:string;agent_name?:string;recipient_ids?:string[];agent_plans?:{agent_id:string;plan:ChatTaskPlan}[]; task_plan?:ChatTaskPlan; kind?: 'connection_request'|'assignment'; awaiting_user?: boolean; received_at?: number; attachments?: ChatFile[]; tool_event?: {name: string; status: "running" | "completed" | "failed"; input?: string; output?: string; output_truncated?: boolean}; id: string; role: 'user' | 'assistant'; text: string; created_at: number; reply_to?: string; final?: boolean }
export interface ChatMember {id:string;name:string;role:'coordinator'|'member';status:'waiting'|'connected'|'offline';paused?:boolean}
export interface ChatOperation {id:string;reply_to:string;agent_id?:string;agent_name:string;tool:string;kind:'read'|'search'|'edit'|'exec'|'other';status:'running'|'completed'|'failed'|'interrupted';started_at:number;duration_ms?:number;paths:string[];input:string;output?:string;diff?:string;truncated?:boolean;dry_run:boolean}
export interface ChatPairing {attempt_id:string;expires_at:number;started_at:number|null}
export interface ChatSession {pairing?:ChatPairing|null;note?:string;connection_id?:string; operations?:ChatOperation[];operations_error?:string;mode?:'work'|'group';members?:ChatMember[];agent_name?:string; pinned?: boolean; archived?: boolean; queued_messages?: ChatMessage[]; queue_mode?: 'merge' | 'split' | 'group' | 'work';member_id?:string; work_state?: 'queued' | 'processing' | null; assistant_message_count?: number; id: string; title: string; created_at: number; updated_at: number; closed: boolean; status: 'waiting' | 'connected' | 'offline' | 'closed'; archive_path: string; messages?: ChatMessage[] }
export interface ChatResult {pairing?:{ticket:string;attempt_id:string;expires_at:number}; deleted?: boolean; chat_id?: string; next_offset?: number; connection_request_id?: string; name?: string; mime?: string; local_only?: boolean; attachment?: ChatFile; data_base64?: string; sessions?: ChatSession[]; session?: ChatSession }
export type ChatAction = { action: 'prepare_pairing'|'set_note'|'set_mode'|'rename_member'|'detach_member'|'resume_member'|'set_coordinator'|'pin' | 'archive' | 'delete' | 'set_queue_mode' | 'upload_chunk' | 'read_attachment_chunk' | 'request_connection' | 'reveal_path' | 'read_artifact' | 'detach' | 'rename' | 'list' | 'create' | 'read' | 'send' | 'close' | 'upload' | 'read_attachment'; pinned?: boolean; archived?: boolean; mode?: 'merge' | 'split' | 'group' | 'work';member_id?:string; offset?: number; total_size?: number; chat_id?: string; message_id?: string; text?: string; note?:string; title?: string; upload_id?: string; name?: string; data_base64?: string; source_path?: string; attachment_ids?: string[] };
export function localChat(workspaceId: string, folderId: string, args: ChatAction): Promise<ChatResult> { return getBackend().chat.request(workspaceId, folderId, args); }

export interface DiscussionDelivery {chat_id:string;message_id:string;title:string;status:string;replies:ChatMessage[];error?:string}
export interface DiscussionPost {summaries?:ChatMessage[];id:string;from:string;name:string;text:string;goal:string;purpose:string;created_at:number;targets:string[];deliveries:DiscussionDelivery[]}
export interface Discussion {paused?:boolean;pinned?:boolean;collaboration?:boolean;coordinator_chat_id?:string;aliases?:Record<string,string>;archive_path?:string;id:string;name:string;goal:string;members:string[];archived:boolean;updated_at:number;posts?:DiscussionPost[];total:number;next_offset?:number|null;member_details?:{id:string;title:string;note:string;status:string;busy?:boolean;error?:boolean}[]}
export interface DiscussionAction {paused?:boolean;pinned?:boolean;collaboration?:boolean;coordinator_chat_id?:string;action:'discussion_list'|'discussion_create'|'discussion_read'|'discussion_update'|'discussion_post';discussion_id?:string;title?:string;goal?:string;member_chat_ids?:string[];archived?:boolean;message_id?:string;text?:string;purpose?:string;recipient_chat_ids?:string[];offset?:number}
export function localDiscussion(workspaceId:string,folderId:string,args:DiscussionAction):Promise<{discussions?:Discussion[];discussion?:Discussion;persisted?:boolean}> {
  return getBackend().chat.request(workspaceId,folderId,args as unknown as ChatAction) as Promise<{discussions?:Discussion[];discussion?:Discussion;persisted?:boolean}>;
}
