<script lang="ts">
  import {page} from '$app/stores';
  import {tick,getContext,onDestroy} from 'svelte';
  import {MOBILE_CHAT_HEADER,type MobileHeaderContext} from '$lib/chat/mobile-header';
  import MobileSheet from '$lib/components/MobileSheet.svelte';
  import Link from '@lucide/svelte/icons/link';
  import Ellipsis from '@lucide/svelte/icons/ellipsis';
  import ArrowUp from '@lucide/svelte/icons/arrow-up';
  import {robotPresence} from '$lib/chat/robot-presence';
  import {discussionLocation} from '$lib/chat/discussion-navigation';
  import {robotQuery,memberTint,discussionTimeline} from '$lib/chat/collaboration';
  import {anchoredChoices} from '$lib/chat/anchored-choices';
  import ChatMarkdown from './ChatMarkdown.svelte';
  import RobotMention from './RobotMention.svelte';
  import {robotMentionParts} from '$lib/chat/robot-mentions';
  import ChatAttachment from './ChatAttachment.svelte';
  import {onMount} from 'svelte';
  import {goto} from '$app/navigation';
  import {appUrl} from '$lib/app-path';
  import {chatLocation} from '$lib/chat/location';
  import {randomId,copyText} from '$lib/browser-tools';
  import {localChat,localDiscussion,type ChatSession,type Discussion,type DiscussionAction} from '$lib/api/chat';
  import {t} from '$lib/i18n';
  import type {MessageKey} from '$lib/i18n/catalog';
  let {workspaceId,folderId}:{workspaceId:string;folderId:string}=$props();
  let groups=$state<Discussion[]>([]),sessions=$state<ChatSession[]>([]),selected=$state($page.url.searchParams.get('discussion')??''),current=$state<Discussion>();
  let error=$state(''),busy=$state(false),loading=$state(true),editing=$state(false),creating=$state(false);
  let name=$state(''),goal=$state(''),members=$state<string[]>([]),text=$state(''),purpose=$state('discussion'),targets=$state<string[]>([]),pages=$state(1);
  let coordinator=$state(''),composer=$state<HTMLTextAreaElement>(),caret=$state(0),focused=$state(false),choiceIndex=$state(0);
  let draftHighlight=$state<HTMLDivElement>();
  const highlightedDraft=$derived(robotMentionParts(text,current?.collaboration?current.aliases:{}));
  const query=$derived(focused&&current?.collaboration?robotQuery(text,caret):null);
  const robotChoices=$derived(query?(current?.member_details??[]).filter(m=>(current?.aliases?.[m.id]??m.title).toLocaleLowerCase().includes(query.query.toLocaleLowerCase())):[]);
  const presenceLabels={online:'chat.98',offline:'chat.memberOffline',working:'chat.70',error:'collab.error'} as const;
  const timeline=$derived(current?discussionTimeline(current):[]);
  function insertRobot(id:string){if(!query||!current)return;const value='#'+(current.aliases?.[id]??id)+' ';text=text.slice(0,query.start)+value+text.slice(query.end);caret=query.start+value.length;focused=false;void tick().then(()=>{composer?.focus();composer?.setSelectionRange(caret,caret);focused=false;});}
  function robotKeys(e:KeyboardEvent){
    if(e.isComposing||e.keyCode===229)return;
    if(query&&robotChoices.length){
      if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();choiceIndex=(choiceIndex+(e.key==='ArrowDown'?1:-1)+robotChoices.length)%robotChoices.length;return;}
      if((e.key==='Enter'&&!e.shiftKey)||e.key==='Tab'){e.preventDefault();insertRobot((robotChoices[choiceIndex]??robotChoices[0]).id);return;}
      if(e.key==='Escape'){e.preventDefault();focused=false;return;}
    }
    if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}
  }
  function mentionRobot(id:string){text+=(text&&!/\s$/.test(text)?' ':'')+'#'+(current?.aliases?.[id]??id)+' ';void tick().then(()=>composer?.focus());}
  let pending=$state<DiscussionAction|null>(null),createId='';let alive=true;
  const choices=$derived(sessions.filter(s=>(!s.closed&&!s.archived&&s.mode!=='group'&&!!s.agent_name)||members.includes(s.id)));
  const missingMembers=$derived(members.filter(id=>!sessions.some(s=>s.id===id)));
  const mobileHeader=getContext<MobileHeaderContext|undefined>(MOBILE_CHAT_HEADER);
  const headerOwner=Symbol('group-header');
  let mobileActions=$state(false),menu=$state<HTMLDivElement>(),editor=$state<HTMLDialogElement>(),copied=$state(false);
  const online=$derived(!current?.paused&&(current?.member_details??[]).some(m=>m.status==='connected'));
  $effect(()=>{mobileHeader?.header.set({owner:headerOwner,title:current?.name??$t('discuss.create'),status:current?.paused?$t('collab.disconnected'):'#'+$t('chat.group'),online,openMenu:()=>mobileActions=true});});
  onDestroy(()=>mobileHeader?.header.update(value=>value?.owner===headerOwner?null:value));
  $effect(()=>{if(editing)editor?.showModal();else editor?.close();});
  async function copyLink(){try{const url=new URL(appUrl(discussionLocation(workspaceId,folderId,selected)),location.origin);await copyText(url.href);copied=true;}catch(e){error=String(e)}}
  async function disconnect(){if(!current||busy||pending)return;busy=true;error='';try{const result=await call({action:'discussion_update',discussion_id:selected,paused:true});if(!result.persisted)throw Error($t('discuss.unconfirmed'));current=result.discussion;mobileActions=false;}catch(e){error=String(e)}finally{busy=false}}
  function cancelEdit(){editing=false;if(!current)void goto(appUrl(chatLocation(workspaceId,folderId)));}

  const states:Record<string,MessageKey>={undelivered:'discuss.undelivered',queued:'discuss.queued',processing:'discuss.processing',completed:'discuss.completed',awaiting_user:'discuss.awaiting',closed:'discuss.closed',unavailable:'discuss.unavailable'};
  const call=(args:DiscussionAction)=>localDiscussion(workspaceId,folderId,args);
  async function read(id:string){
    const result=await call({action:'discussion_read',discussion_id:id});let next=result.discussion;
    for(let page=1;next?.next_offset!=null&&page<pages;page++){
      const older=(await call({action:'discussion_read',discussion_id:id,offset:next.next_offset})).discussion;
      if(!older)break;next={...next,posts:[...(older.posts??[]),...(next.posts??[])],next_offset:older.next_offset};
    }
    if(alive&&selected===id){current=next;targets=targets.filter(id=>next?.members.includes(id));}
  }
  async function refresh(){
    const [list,chats]=await Promise.all([call({action:'discussion_list'}),localChat(workspaceId,folderId,{action:'list'})]);
    if(!alive)return;groups=list.discussions??[];sessions=chats.sessions??[];
    if(!selected&&!editing){const first=groups.find(g=>!g.archived);if(first){await goto(appUrl(discussionLocation(workspaceId,folderId,first.id)),{replaceState:true});return;}edit(true);}
    if(selected)await read(selected);
  }
  onMount(()=>{alive=true;if($page.url.searchParams.get('createGroup')==='1')edit(true);let timer:ReturnType<typeof setTimeout>;async function poll(){try{if(!busy)await refresh()}catch(e){if(alive)error=String(e)}finally{if(alive){loading=false;timer=setTimeout(poll,3000)}}}void poll();return()=>{alive=false;clearTimeout(timer)}});
  function edit(fresh=false){if(pending)return;creating=fresh;editing=true;name=fresh?'':current?.name??'';goal=fresh?'':current?.goal??'';members=fresh?[]:[...(current?.members??[])];coordinator=fresh?'':current?.coordinator_chat_id??current?.members[0]??'';if(fresh)createId=randomId();error='';}
  async function save(){if(busy)return;busy=true;error='';try{const result=await call({action:creating?'discussion_create':'discussion_update',discussion_id:creating?createId:selected,title:name,goal,member_chat_ids:members,collaboration:creating?true:current?.collaboration,coordinator_chat_id:members.includes(coordinator)?coordinator:members[0],paused:false});if(result.discussion){selected=result.discussion.id;current=result.discussion;}editing=false;if(creating){await goto(appUrl(discussionLocation(workspaceId,folderId,selected)),{replaceState:true});}else await refresh()}catch(e){error=String(e)}finally{busy=false}}
  async function archive(){if(!current||busy||pending)return;busy=true;error='';try{await call({action:'discussion_update',discussion_id:selected,archived:!current.archived});menu?.hidePopover();await refresh()}catch(e){error=String(e)}finally{busy=false}}
  async function send(){if(busy||current?.paused||(!pending&&!text.trim()))return;busy=true;error='';try{pending??={action:'discussion_post',discussion_id:selected,message_id:randomId(),text,purpose,...(targets.length?{recipient_chat_ids:[...targets]}:current?.collaboration?{}:{recipient_chat_ids:[...(current?.members??[])]})};const result=await call(pending);if(!result.persisted)throw Error($t('discuss.unconfirmed'));pending=null;text='';pages=1;await refresh()}catch(e){error=String(e)}finally{busy=false}}
  async function more(){busy=true;pages++;try{await read(selected)}catch(e){pages--;error=String(e)}finally{busy=false}}
  function open(id:string){void goto(appUrl(chatLocation(workspaceId,folderId,id)))}
</script>
<dialog class="group-editor" bind:this={editor} oncancel={event=>{event.preventDefault();cancelEdit()}}><form onsubmit={event=>{event.preventDefault();void save()}}><h2>{$t(creating?'discuss.create':'discuss.manage')}</h2>{#if error}<p role="alert">{error}</p>{/if}<label>{$t('Name')}<input bind:value={name} maxlength="80" required disabled={busy}/></label><label>{$t('discuss.goal')}<textarea bind:value={goal} maxlength="1000" rows="3" disabled={busy}></textarea></label><fieldset disabled={busy}><legend>{$t('discuss.choose')}</legend>{#each choices as s (s.id)}<label><input type="checkbox" value={s.id} bind:group={members}/><span>{s.agent_name??s.title}<small>{s.title} · {$t(s.status==='offline'?'chat.memberOffline':s.work_state==='processing'?'chat.70':'Connected')}</small></span></label>{:else}<p>{$t('discuss.noSessions')}</p>{/each}{#each missingMembers as id}<label><input type="checkbox" value={id} bind:group={members}/><span>{current?.member_details?.find(m=>m.id===id)?.title??id}<small>{$t('discuss.unavailable')}</small></span></label>{/each}</fieldset><label>{$t('chat.coordinator')}<select bind:value={coordinator} disabled={busy||!members.length}><option value="">{$t('collab.firstCoordinator')}</option>{#each members as id}<option value={id}>{sessions.find(s=>s.id===id)?.agent_name??current?.member_details?.find(m=>m.id===id)?.title??id}</option>{/each}</select></label><footer><button type="button" onclick={cancelEdit} disabled={busy}>{$t('Cancel')}</button><button type="submit" disabled={busy||!name.trim()||!members.length}>{$t('Save')}</button></footer></form>
</dialog>
{#if mobileActions}<MobileSheet title={$t('mobile.chatActions')} onClose={()=>mobileActions=false}><div class="mobile-group-actions"><button onclick={()=>{mobileActions=false;edit()}} disabled={busy||!!pending}>{$t('chat.connect')}</button><button onclick={disconnect} disabled={busy||!!pending||!current||!!current.paused}>{$t('chat.disconnect')}</button><button onclick={copyLink} disabled={!current}>{$t(copied?'collab.linkCopied':'collab.copyLink')}</button><button onclick={()=>{mobileActions=false;void archive()}} disabled={busy||!!pending||!current}>{$t(current?.archived?'chat.unarchive':'chat.archive')}</button></div></MobileSheet>{/if}
<div class="discussions">
  <section>
    {#if error}<p role="alert">{error}</p>{/if}
    {#if current}<header class="group-heading"><div class="group-title"><h2 title={current.name}>{current.name}</h2><span class="group-mode">#{$t('chat.group')}</span></div><div class="members" aria-label={$t('collab.robots')}>{#each current.member_details??[] as member}{@const presence=robotPresence(member)}<button onclick={()=>current?.collaboration?mentionRobot(member.id):open(member.id)} disabled={member.status==='missing'||!!current.paused} title={`${member.title} · ${$t(presenceLabels[presence])}${member.id===current.coordinator_chat_id?' · '+$t('chat.coordinator'):''}${member.note?' · '+member.note:''}`} aria-label={`${member.title} · ${$t(presenceLabels[presence])}`} data-presence={presence} style:--member-color={memberTint(member.id)}><span class="robot-status" aria-hidden="true"></span>{current.collaboration?'#':''}{member.title}</button>{/each}</div><div class="header-actions"><div class="connection-actions"><button onclick={disconnect} disabled={busy||!!pending||!!current.paused||current.archived}>{$t('chat.disconnect')}</button><button onclick={()=>edit()} disabled={busy||!!pending||current.archived}>{$t('chat.connect')}</button></div><button class="icon-button" onclick={copyLink} title={$t(copied?'collab.linkCopied':'collab.copyLink')} aria-label={$t('collab.copyLink')}><Link size={16}/></button><button class="icon-button" onclick={()=>menu?.showPopover()} title={$t('chat.conversationActions')} aria-label={$t('chat.conversationActions')}><Ellipsis size={18}/></button></div></header>
      <div class="group-menu" bind:this={menu} popover="auto"><button onclick={()=>{menu?.hidePopover();edit()}} disabled={busy||!!pending}>{$t('discuss.manage')}</button><button onclick={archive} disabled={busy||!!pending}>{$t(current.archived?'chat.unarchive':'chat.archive')}</button></div>

      {#if current.paused}<p class="hint disconnected">{$t('collab.disconnectedHint')}</p>{/if}
      <div class="feed"><div class="message-column">{#if current.next_offset!=null}<button onclick={more} disabled={busy}>{$t('discuss.more')}</button>{/if}
      {#if current.collaboration}
      {#each timeline as row (row.id)}<article class="collab-card" class:user={row.memberId==='user'} style:--member-color={memberTint(row.memberId)}><header><strong>{row.memberName}</strong><small>{new Date(row.created_at).toLocaleString()}</small></header><ChatMarkdown text={row.text} attachments={row.attachments??[]} {workspaceId} {folderId} chatId={row.sourceChatId} robotAliases={current.aliases}/>{#each row.attachments??[] as file (file.id)}<ChatAttachment {workspaceId} {folderId} chatId={row.sourceChatId} {file}/>{/each}</article>{:else}<p>{$t('discuss.start')}</p>{/each}
      <div class="delivery-status">{#each (current.posts??[]).flatMap(p=>p.deliveries).filter(d=>d.status!=='completed') as delivery}<small>{current.aliases?.[delivery.chat_id]??delivery.title} · {$t(states[delivery.status]??'discuss.unavailable')}</small>{/each}</div>
      {:else}{#each current.posts??[] as post (post.id)}<article><header><strong>{post.name}</strong><span>{$t(('discuss.'+post.purpose) as MessageKey)}</span><small>{new Date(post.created_at).toLocaleString()}</small></header><p class="message">{post.text}</p><small class="task-id">{$t('discuss.id')}: {post.id}</small><div class="deliveries">{#each post.deliveries as delivery}<details open={post.purpose==='task'}><summary><span>{delivery.title}</span><span class:done={delivery.status==='completed'}>{$t(states[delivery.status]??'discuss.unavailable')}</span></summary>{#if delivery.error}<p role="alert">{delivery.error}</p>{/if}{#each delivery.replies as reply (reply.id)}<div class="result"><small>{$t(reply.final?'discuss.result':'discuss.progress')}</small><p class="message">{reply.text}</p>{#if reply.attachments?.length}<small>{$t('discuss.attachments')}</small>{/if}</div>{/each}<button onclick={()=>open(delivery.chat_id)}>{$t('discuss.open')}</button></details>{/each}</div></article>{:else}<p>{$t('discuss.start')}</p>{/each}{/if}</div></div>
      {#if !current.archived}<div class="composer-area"><form class="composer" onsubmit={event=>{event.preventDefault();void send()}}>{#if !current.collaboration}<div class="send-options"><label>{$t('discuss.purpose')}<select bind:value={purpose} disabled={busy||!!pending}>{#each ['discussion','question','notice','task'] as value}<option {value}>{$t(('discuss.'+value) as MessageKey)}</option>{/each}</select></label><details><summary>{$t('discuss.recipients')} · {targets.length||(current.collaboration?$t('chat.coordinator'):current.members.length)}</summary><p>{$t(current.collaboration?'collab.defaultTargets':'discuss.allHint')}</p>{#each current.member_details??[] as member}<label><input type="checkbox" value={member.id} bind:group={targets} disabled={busy||!!pending}/>{member.title}</label>{/each}</details></div>{/if}<div class="group-input"><div class="draft-highlight" bind:this={draftHighlight} aria-hidden="true">{#each highlightedDraft as part}{#if part.memberId}<RobotMention text={part.text} memberId={part.memberId}/>{:else}{part.text}{/if}{/each}{'\n'}</div><textarea bind:this={composer} bind:value={text} oninput={()=>{caret=composer?.selectionStart??0;focused=true;choiceIndex=0}} onfocus={()=>{focused=true;caret=composer?.selectionStart??0}} onblur={()=>focused=false} onkeyup={()=>caret=composer?.selectionStart??0} onclick={()=>{focused=true;caret=composer?.selectionStart??0}} onscroll={()=>{if(draftHighlight&&composer){draftHighlight.scrollTop=composer.scrollTop;draftHighlight.scrollLeft=composer.scrollLeft}}} onkeydown={robotKeys} aria-label={$t('discuss.message')} placeholder={$t('discuss.message')} rows="3" maxlength="8000" disabled={busy||!!pending||!!current.paused}></textarea>{#if query&&robotChoices.length}<div class="robot-choices" role="listbox" aria-label={$t('collab.robots')} popover="manual" use:anchoredChoices={()=>composer}>{#each robotChoices as robot,i (robot.id)}<button type="button" role="option" aria-selected={choiceIndex===i} class:active={choiceIndex===i} onpointerdown={e=>e.preventDefault()} onclick={()=>insertRobot(robot.id)}>#{current.aliases?.[robot.id]??robot.title}</button>{/each}</div>{/if}</div>{#if pending}<p>{$t('discuss.retryHint')}</p>{/if}<button class="send-button" type="submit" aria-label={$t(pending?'discuss.retry':'discuss.send')} title={$t('discuss.send')} disabled={busy||!!current.paused||(!pending&&!text.trim())}><ArrowUp size={18}/></button></form></div>{/if}
    {:else if loading}<p>{$t('Loading…')}</p>{:else}<div class="group-empty"><h2>{$t('discuss.create')}</h2><button onclick={()=>edit(true)}>{$t('chat.connect')}</button></div>{/if}
  </section>
</div>
<style>
.discussions{height:100%;min-height:0;display:flex;flex-direction:column;background:var(--card-bg);font-size:13px;color:var(--color-text)}.discussions>section{display:flex;flex:1;flex-direction:column;min-height:0;overflow:hidden}button{cursor:pointer;border-radius:7px}button:hover:enabled{background:var(--surface-hover)}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--primary);outline-offset:2px}
.group-heading{min-height:60px;flex:none;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 26px;border-bottom:1px solid var(--color-border)}.group-title{display:flex;gap:12px;align-items:center;min-width:0;max-width:30%;flex:none}.group-title h2{font-size:13px;font-weight:550;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.group-mode{font-size:11px;color:var(--color-text-muted);white-space:nowrap}.header-actions{display:flex;align-items:center;gap:14px;flex:none;font-size:11px;color:var(--color-text-muted)}.connection-actions{display:flex;border:1px solid var(--color-border);border-radius:9px;overflow:hidden}.connection-actions button{padding:7px 13px;border-radius:0}.connection-actions button+button{border-left:1px solid var(--color-border)}.icon-button{display:grid;place-items:center;padding:5px}
.members{display:flex;flex:1;min-width:0;flex-wrap:nowrap;gap:7px;overflow-x:auto;padding:2px 0;scrollbar-width:thin}.members button{display:flex;align-items:center;gap:6px;flex:none;white-space:nowrap;padding:6px 9px;border:1px solid color-mix(in srgb,var(--member-color) 30%,var(--color-border));background:color-mix(in srgb,var(--member-color) 7%,var(--card-bg));font-size:12px}.members span{width:6px;height:6px;border-radius:50%;background:#888}.members [data-presence=online] .robot-status{background:#35b27c}.members [data-presence=offline] .robot-status{background:#e36767}.members [data-presence=error] .robot-status{background:#e4b641}.members [data-presence=working] .robot-status{background:#619ff0}small{font-size:10px;color:var(--color-text-muted)}
.feed{flex:1;min-height:0;overflow-y:auto}.message-column{max-width:800px;margin:auto;padding:25px 40px 30px}.feed article{margin-bottom:22px;padding:14px 17px;border:1px solid var(--color-border);border-radius:14px;background:var(--surface-2);overflow-wrap:anywhere}.feed article header{display:flex;align-items:center;gap:10px;margin-bottom:8px;font-size:11px}.collab-card{background:color-mix(in srgb,var(--member-color) 9%,var(--card-bg))!important;border-color:color-mix(in srgb,var(--member-color) 24%,var(--color-border))!important}.collab-card.user{margin-left:14%;border-radius:14px 14px 3px 14px}.message{white-space:pre-wrap;line-height:1.7}.delivery-status{display:flex;flex-wrap:wrap;gap:8px}.deliveries{display:grid;gap:7px;margin-top:12px}.result{border-left:2px solid var(--color-border);padding:8px;margin:8px 0}.task-id{display:block;overflow-wrap:anywhere}details{border:1px solid var(--color-border);border-radius:8px;padding:8px}summary{cursor:pointer}summary span+span{margin-left:12px;color:var(--color-text-muted)}summary .done{color:#36a578}
.composer-area{flex:none;padding:12px 30px 20px}.composer{max-width:760px;margin:auto;padding:14px 16px 10px;border:1px solid var(--color-border);border-radius:17px;background:var(--surface-2)}.group-input textarea,.draft-highlight{box-sizing:border-box;width:100%;padding:0;border:0;font-family:inherit;font-size:13px;font-weight:400;line-height:1.7;letter-spacing:normal;white-space:pre-wrap;overflow-wrap:break-word;word-break:normal;tab-size:8}.group-input textarea{display:block;position:relative;z-index:1;resize:none;scrollbar-width:none;min-height:62px;max-height:160px;background:transparent;outline:none;color:transparent;caret-color:var(--color-text)}.group-input textarea::-webkit-scrollbar{display:none}.draft-highlight{position:absolute;inset:0;height:100%;pointer-events:none;overflow:hidden;color:var(--color-text)}.send-button{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:#2c67c5;color:#fff;margin:7px 0 0 auto}.send-button:hover:enabled{background:#2c67c5;opacity:.9}.send-options{display:flex;gap:12px;margin-bottom:12px}.send-options label{display:flex;gap:8px}.group-input{position:relative}
.robot-choices{position:fixed;inset:auto;margin:0;padding:6px;border:1px solid var(--color-border);border-radius:12px;background:var(--surface-2);color:var(--color-text);overflow:auto;box-shadow:0 12px 32px #0007}.robot-choices button{display:block;width:100%;padding:7px 10px;text-align:left}.robot-choices .active{background:var(--surface-hover)}.hint{padding:8px 26px;font-size:11px;color:var(--color-text-muted)}[role=alert]{color:var(--danger);padding:10px 26px;overflow-wrap:anywhere}.group-empty{text-align:center;margin:auto}.group-empty button{padding:10px 18px;border:1px solid var(--color-border);margin-top:12px}
.group-editor{margin:auto;width:min(560px,calc(100vw - 28px));max-height:calc(100dvh - 28px);overflow:auto;padding:24px;border:1px solid var(--color-border);border-radius:18px;background:var(--color-bg);color:var(--color-text)}.group-editor::backdrop{background:#0007;backdrop-filter:blur(5px)}.group-editor h2{font-size:17px;font-weight:600}.group-editor label{display:flex;gap:9px;margin:12px 0}.group-editor form>label{flex-direction:column}.group-editor input:not([type=checkbox]),.group-editor textarea,.group-editor select{width:100%;min-width:0;padding:9px;border:1px solid var(--color-border);border-radius:8px;background:var(--card-bg)}.group-editor fieldset{max-height:260px;overflow:auto;padding:12px;border:1px solid var(--color-border);border-radius:10px}.group-editor fieldset small{display:block}.group-editor footer{display:flex;gap:10px;justify-content:flex-end;margin-top:16px}.group-editor footer button{padding:8px 14px;border:1px solid var(--color-border)}.group-menu{position:fixed;inset:100px 20px auto auto;margin:0;padding:6px;min-width:170px;background:var(--color-bg);color:var(--color-text);border:1px solid var(--color-border);border-radius:10px}.group-menu button,.mobile-group-actions button{display:block;width:100%;padding:10px;text-align:left}.mobile-group-actions{display:grid;gap:8px}
@media(max-width:700px){.group-heading{padding:10px 12px;min-height:48px}.group-title{display:none}.header-actions{display:none}.members{padding:0}.members button{font-size:11px}.message-column{padding:18px 12px}.composer-area{padding:8px 12px 12px}.hint{padding:8px 12px}.group-menu{top:110px;right:12px}.group-editor{padding:18px}}
</style>
