pub const P0_TOOLS: &[(&str, &str, &str, bool, bool, bool)] = &[
    (
        "chat_open",
        "Chat open",
        "Attach to a client-created chat; read returned skill.text and session records, save attachment_id, then call chat_wait. Renew with the same ID before the 10-minute lease expires; never take another attachment.",
        false,
        false,
        false,
    ),
    (
        "chat_wait",
        "Chat wait",
        "Wait for one user message using the saved attachment_id; only one wait at a time. idle: immediately wait again. message: work and chat_reply. closed: stop.",
        false,
        false,
        false,
    ),
    (
        "chat_upload",
        "Chat upload",
        "Attach a file under mcp-assistant/artifacts/ via source_path, or bytes up to 512 KiB. Use current attachment_id and stable upload_id for retries; pass returned attachment.id to chat_reply attachment_ids. Never upload credentials.",
        false,
        false,
        false,
    ),
    (
        "chat_reply",
        "Chat reply",
        "Persist a reply to reply_to using a unique message_id. Progress: final=false. Done/question: final=true; questions also awaiting_user=true. Require persisted=true; retries keep the entire payload. Then chat_wait; final does not close the chat.",
        false,
        false,
        false,
    ),
    (
        "chat_close",
        "Chat close",
        "Close a local chat only when the user explicitly ends the conversation.",
        false,
        false,
        false,
    ),

    (
        "harness_status",
        "Harness status",
        "Return durable task, workspace, capability, and recovery status.",
        true,
        false,
        false,
    ),
    (
        "operation_log",
        "Operation log",
        "Return Workspace-level operation history independent of Task state.",
        true,
        false,
        false,
    ),
    (
        "server_info",
        "Server info",
        "Return server, workspace, auth, profile, and exposed-tool metadata.",
        true,
        false,
        false,
    ),
    (
        "list_workspace_folders",
        "List tool hub folders",
        "List folders configured in this tool hub and show the selected or default routing context.",
        true,
        false,
        false,
    ),
    (
        "conversation_bootstrap",
        "Bootstrap conversation workspace",
        "Bind an existing, explicit, or unambiguous workspace folder and initialize compact session history in one call. If multiple folders are unselected, return choices without accessing project content.",
        false,
        false,
        false,
    ),
    (
        "switch_workspace_folder",
        "Switch conversation folder",
        "Select an allowed folder for this conversation without reconnecting; each folder retains independent history.",
        false,
        false,
        false,
    ),
    (
        "query_tool_usage",
        "Query tool usage",
        "Query redacted tool-call history and summaries: errors, latency, traffic, async lifetimes and batching/conflict evidence. Use to diagnose tool execution.",
        true,
        false,
        false,
    ),
    (
        "history_session_bootstrap",
        "Initialize or restore development session",
        "Initialize/resume history for a bound folder; conversation_bootstrap normally does this. Defaults to compact summaries; request full detail when needed.",
        false,
        false,
        false,
    ),
    (
        "history_session_checkpoint",
        "Save development checkpoint",
        "Save an idempotent, redacted handoff. Pass unchanged session_key and expected_path from bootstrap; require ok=true and matching path. turn_id is optional and deterministic.",
        false,
        false,
        false,
    ),
    (
        "history_session_validate",
        "Validate session archive",
        "Validate history numbering, files, session mappings, and optionally rebuild the derived index without deleting history.",
        false,
        false,
        false,
    ),
    (
        "project_state",
        "Project state",
        "Return the current project, task, change, and verification state.",
        true,
        false,
        false,
    ),
    (
        "start_task",
        "Start task",
        "Start a durable coding task and capture the workspace baseline.",
        false,
        false,
        false,
    ),
    (
        "update_task",
        "Update task",
        "Update task steps and durable progress.",
        false,
        false,
        false,
    ),
    (
        "pause_task",
        "Pause task",
        "Pause the active coding task.",
        false,
        false,
        false,
    ),
    (
        "resume_task",
        "Resume task",
        "Resume a paused or failed coding task.",
        false,
        false,
        false,
    ),
    (
        "fail_task",
        "Fail task",
        "Mark an active or verifying task as recoverably failed without emitting a terminal learning outcome.",
        false,
        false,
        false,
    ),
    (
        "close_failed_task",
        "Close failed task",
        "Finalize a failed task as terminal failure and emit the task failure learning outcome.",
        false,
        false,
        false,
    ),
    (
        "rollback_task",
        "Rollback task",
        "Finalize a failed task as rolled back only after the workspace matches its original baseline.",
        false,
        false,
        false,
    ),
    (
        "finish_task",
        "Finish task",
        "Finish a task with verification status and change summary.",
        false,
        false,
        false,
    ),
    (
        "task_context",
        "Task context",
        "Return a bounded durable task context for a new conversation.",
        true,
        false,
        false,
    ),
    (
        "list_task_events",
        "List task events",
        "Read task event history with pagination.",
        true,
        false,
        false,
    ),
    (
        "change_summary",
        "Change summary",
        "Explain what changed, why, and what evidence exists.",
        true,
        false,
        false,
    ),
    (
        "exec_health_check",
        "Exec health check",
        "Verify the exec worker, session creation, command execution, and stdout/stderr capture.",
        true,
        false,
        false,
    ),
    (
        "set_default_cwd",
        "Set default cwd",
        "Set the default cwd for relative tool paths inside the workspace.",
        false,
        false,
        false,
    ),
    (
        "set_todos",
        "Set task checklist",
        "Publish the full checklist for multi-step work. Mark each step in_progress before work and completed after; at most 24 unique IDs and one in_progress. Empty todos clears the list. For local chat pass chat_id, attachment_id, reply_to and workspace_folder_id to persist a plan for that message.",
        false,
        false,
        false,
    ),
    (
        "update_plan",
        "Update plan",
        "Replace the full ordered plan (pending/in_progress/completed); unchanged titles retain IDs. Optional explanation updates progress. Same limits and chat scope parameters as set_todos.",
        false,
        false,
        false,
    ),
    (
        "report_progress",
        "Report progress",
        "Report a meaningful milestone in the task panel, with optional phase and 0-100 percent. todo_id defaults to the in_progress step.",
        false,
        false,
        false,
    ),
    (
        "read_file",
        "Read file",
        "Read a UTF-8 text file slice inside the configured workspace.",
        true,
        false,
        false,
    ),
    (
        "read_many",
        "Read many files",
        "Read multiple bounded UTF-8 file slices with hashes in one call.",
        true,
        false,
        false,
    ),
    (
        "project_map",
        "Project map",
        "Summarize manifests, languages, entrypoints, tests, commands, and a bounded project tree.",
        true,
        false,
        false,
    ),
    (
        "list_files",
        "List workspace entries",
        "List workspace files, directories, or symlinks using glob, depth, and entry-type filters.",
        true,
        false,
        false,
    ),
    (
        "search_text",
        "Search text",
        "Search UTF-8 workspace files for text or regex matches.",
        true,
        false,
        false,
    ),
    (
        "apply_patch",
        "Apply patch",
        "Apply a patch envelope transactionally inside the workspace.",
        false,
        true,
        false,
    ),
    (
        "edit",
        "Edit files",
        "Apply guarded text or line edits to one or more files as one atomic transaction. Text, context, and line targeting are selected through edit parameters while preserving each file's newline style.",
        false,
        true,
        false,
    ),
    (
        "file_ops",
        "File operations",
        "Create, delete (files or directories; non-empty directories need confirm=true), copy, move, or create directories with transactional preflight.",
        false,
        true,
        false,
    ),
    (
        "format_files",
        "Format files",
        "Plan, check, or apply multi-language formatting in an isolated mirror with bounded diffs and guarded workspace writes.",
        false,
        true,
        false,
    ),
    (
        "patch_check",
        "Check patch",
        "Validate a patch without changing the workspace.",
        true,
        false,
        false,
    ),
    (
        "exec_command",
        "Execute command",
        "Run a bounded command in the workspace under runtime policy. Use job_timeout_ms plus a stable operation_id for an authorized long-running process; wait_command controls response waiting only and never extends the fixed process deadline. When a session is retained, continue with wait_command using next_actions.",
        false,
        true,
        true,
    ),
    (
        "exec_many",
        "Execute command graph",
        "Run up to 256 command requests; prefer mode=auto for independent commands. Runtime locks/safety rules may serialize them. Inspect command_ok, graph_execution_ok, failed_command_ids and skipped_command_ids; tool ok alone does not mean commands passed.",
        false,
        true,
        true,
    ),
    (
        "wait_command",
        "Wait for command",
        "Wait for an exec_command session to produce new sequenced output, exit, or finish verification. This wait window is separate from the fixed child-process deadline and never renews timeout_ms or job_timeout_ms.",
        true,
        false,
        false,
    ),
    (
        "resolve_operation",
        "Resolve command operation",
        "Reattach to a retained command by operation_id or command_fingerprint without starting a duplicate process.",
        true,
        false,
        false,
    ),
    (
        "list_sessions",
        "List command sessions",
        "List bounded retained command sessions for recovery, diagnosis, and orphan cleanup.",
        true,
        false,
        false,
    ),
    (
        "send_input",
        "Send command input",
        "Write stdin or close stdin for a running command session without waiting for output.",
        false,
        false,
        false,
    ),
    (
        "kill_session",
        "Kill session",
        "Terminate a server-managed running command session.",
        false,
        true,
        false,
    ),
    (
        "read_output",
        "Read output",
        "Read retained stdout or stderr by output_ref with per-stream byte offset pagination.",
        true,
        false,
        false,
    ),
    (
        "git_status",
        "Git status",
        "Return git working tree status for the workspace.",
        true,
        false,
        false,
    ),
    (
        "git_diff",
        "Git diff",
        "Return unified git diff for workspace changes.",
        true,
        false,
        false,
    ),
    (
        "git_log",
        "Git log",
        "Return recent git commits with bounded structured metadata.",
        true,
        false,
        false,
    ),
    (
        "git_show",
        "Git show",
        "Return bounded git show output for a revision.",
        true,
        false,
        false,
    ),
    (
        "git_blame",
        "Git blame",
        "Return bounded git blame metadata for a workspace file.",
        true,
        false,
        false,
    ),
    (
        "git_branch",
        "Git branch",
        "Create, switch, or delete a Git branch with expected-HEAD guards.",
        false,
        true,
        false,
    ),
    (
        "git_worktree",
        "Git worktree",
        "List, create, or remove linked Git worktrees with guarded cleanup and cwd recovery.",
        false,
        true,
        false,
    ),
    (
        "git_stage",
        "Git stage",
        "Stage selected paths or all workspace changes with structured results.",
        false,
        true,
        false,
    ),
    (
        "git_commit",
        "Git commit",
        "Create a guarded Git commit and return the new commit and repository status.",
        false,
        true,
        false,
    ),
    (
        "git_push",
        "Git push",
        "Push the current or selected branch to a remote with expected-HEAD guards and structured authentication errors.",
        false,
        false,
        true,
    ),
    (
        "git_restore",
        "Git restore",
        "Restore or unstage selected paths with explicit confirmation.",
        false,
        true,
        false,
    ),
    (
        "request_permissions",
        "Approve and resume operation",
        "Approve and immediately resume one pending permission-gated operation.",
        false,
        true,
        false,
    ),
    (
        "view_image",
        "View image",
        "Return a workspace image as MCP image content.",
        true,
        false,
        false,
    ),
    (
        "desktop_displays",
        "List desktop displays",
        "List physical desktop displays with local sizes and global virtual-desktop origins.",
        false,
        false,
        false,
    ),
    (
        "desktop_screenshot",
        "Capture desktop display",
        "Capture one display at native pixel dimensions with JPEG quality compression and no resizing.",
        false,
        false,
        false,
    ),
    (
        "desktop_click",
        "Click desktop",
        "Move to display-local physical pixel coordinates and click a mouse button.",
        false,
        true,
        false,
    ),
    (
        "desktop_drag",
        "Drag desktop",
        "Hold a mouse button and drag between display-local physical pixel coordinates, including across displays.",
        false,
        true,
        false,
    ),
    (
        "desktop_scroll",
        "Scroll desktop",
        "Scroll the desktop, optionally at display-local physical pixel coordinates.",
        false,
        true,
        false,
    ),
    (
        "desktop_type",
        "Type desktop text",
        "Type Unicode text into the currently focused desktop application.",
        false,
        true,
        false,
    ),
    (
        "desktop_key",
        "Press desktop keys",
        "Press a key or hotkey chord in the currently focused desktop application.",
        false,
        true,
        false,
    ),
];

/// old Python 版本默认提供的核心工具集。默认 MCP 只暴露这一组，保持 Agent 的工具面稳定。
pub const CORE_TOOLS: &[&str] = &[
    "chat_open",
    "chat_wait",
    "chat_reply",
    "chat_upload",
    "chat_close",
    "server_info",
    "list_workspace_folders",
    "conversation_bootstrap",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "set_default_cwd",
    "set_todos",
    "update_plan",
    "report_progress",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_worktree",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "view_image",
];

pub const GUARDED_CORE_TOOLS: &[&str] = &[
    "chat_open",
    "chat_wait",
    "chat_reply",
    "chat_upload",
    "chat_close",
    "server_info",
    "list_workspace_folders",
    "conversation_bootstrap",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "set_default_cwd",
    "set_todos",
    "update_plan",
    "report_progress",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_worktree",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "request_permissions",
    "view_image",
];

pub const CORE_READ_ONLY_TOOLS: &[&str] = &[
    "server_info",
    "list_workspace_folders",
    "query_tool_usage",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "view_image",
];

pub const ALLOWED_TOOLS: &[&str] = &[
    "chat_open",
    "chat_wait",
    "chat_reply",
    "chat_upload",
    "chat_close",
    "harness_status",
    "operation_log",
    "server_info",
    "list_workspace_folders",
    "conversation_bootstrap",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "history_session_validate",
    "exec_health_check",
    "set_default_cwd",
    "set_todos",
    "update_plan",
    "report_progress",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "patch_check",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_worktree",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "project_state",
    "start_task",
    "update_task",
    "pause_task",
    "resume_task",
    "fail_task",
    "close_failed_task",
    "rollback_task",
    "finish_task",
    "task_context",
    "list_task_events",
    "change_summary",
    "request_permissions",
    "view_image",
    "desktop_displays",
    "desktop_screenshot",
    "desktop_click",
    "desktop_drag",
    "desktop_scroll",
    "desktop_type",
    "desktop_key",
];

pub const READ_ONLY_TOOLS: &[&str] = coding_tools_tunnel_protocol::MCP_READ_ONLY_TOOL_NAMES;

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::{
        ALLOWED_TOOLS, CORE_READ_ONLY_TOOLS, CORE_TOOLS, GUARDED_CORE_TOOLS, P0_TOOLS,
        READ_ONLY_TOOLS,
    };

    #[test]
    fn metadata_sets_reference_unique_declared_tools() {
        let declared: HashSet<_> = P0_TOOLS.iter().map(|(name, ..)| *name).collect();
        assert_eq!(declared.len(), P0_TOOLS.len(), "duplicate P0 tool metadata");

        for (label, names) in [
            ("allowed", ALLOWED_TOOLS),
            ("trusted core", CORE_TOOLS),
            ("guarded core", GUARDED_CORE_TOOLS),
            ("read-only core", CORE_READ_ONLY_TOOLS),
            ("retry-safe", READ_ONLY_TOOLS),
        ] {
            let unique: HashSet<_> = names.iter().copied().collect();
            assert_eq!(unique.len(), names.len(), "duplicate {label} tool");
            assert!(
                unique.is_subset(&declared),
                "{label} metadata references an undeclared tool"
            );
        }
    }
}
